// Generated by CoffeeScript 1.12.4
var Scene;

Scene = require("./Scene");

Scene.Chain = require("./SceneChain");

Scene.Collection = require("./SceneCollection");

Scene.Router = require("./SceneRouter");

module.exports = Scene;
